In [1]:
# Importing the libraries
import numpy as np
import pandas as pd

In [2]:

# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')

dataset

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [3]:
X = dataset.iloc[:, 3:13]
y = dataset.iloc[:, 13]

In [4]:

#Create dummy variables
geography=pd.get_dummies(X["Geography"],drop_first=True)
gender=pd.get_dummies(X['Gender'],drop_first=True)

In [5]:

## Concatenate the Data Frames

X=pd.concat([X,geography,gender],axis=1)

## Drop Unnecessary columns
X=X.drop(['Geography','Gender'],axis=1)

In [6]:

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [7]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:


# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LeakyReLU,PReLU,ELU
from keras.layers import Dropout

Using TensorFlow backend.

In [10]:
classifier = Sequential()
classifier.add(Dense(units = 6, kernel_initializer = 'he_uniform',activation='relu',input_dim = 11))
classifier.add(Dense(units = 6, kernel_initializer = 'he_uniform',activation='relu'))
classifier.add(Dense(units = 1, kernel_initializer = 'glorot_uniform', activation = 'sigmoid'))
classifier.compile(optimizer = 'Adamax', loss = 'binary_crossentropy', metrics = ['accuracy'])
model_history=classifier.fit(X_train, y_train,validation_split=0.33, batch_size = 10, epochs = 50)

Train on 5359 samples, validate on 2641 samples
Epoch 1/50
5359/5359 [==============================] - 1s 148us/step - loss: 0.6634 - accuracy: 0.6800 - val_loss: 0.4916 - val_accuracy: 0.7997
Epoch 2/50
5359/5359 [==============================] - 1s 119us/step - loss: 0.4690 - accuracy: 0.8054 - val_loss: 0.4593 - val_accuracy: 0.8042
Epoch 3/50
5359/5359 [==============================] - 1s 116us/step - loss: 0.4437 - accuracy: 0.8128 - val_loss: 0.4473 - val_accuracy: 0.8099
Epoch 4/50
5359/5359 [==============================] - 1s 115us/step - loss: 0.4320 - accuracy: 0.8160 - val_loss: 0.4414 - val_accuracy: 0.8080
Epoch 5/50
5359/5359 [==============================] - 1s 123us/step - loss: 0.4247 - accuracy: 0.8188 - val_loss: 0.4381 - val_accuracy: 0.8073
Epoch 6/50
5359/5359 [==============================] - 1s 144us/step - loss: 0.4193 - accuracy: 0.8199 - val_loss: 0.4325 - val_accuracy: 0.8076
Epoch 7/50
5359/5359 [==============================] - 1s 143us/step - loss: 0.4136 - accuracy: 0.8218 - val_loss: 0.4271 - val_accuracy: 0.8095
Epoch 8/50
5359/5359 [==============================] - 1s 142us/step - loss: 0.4072 - accuracy: 0.8253 - val_loss: 0.4225 - val_accuracy: 0.8065
Epoch 9/50
5359/5359 [==============================] - 1s 140us/step - loss: 0.4008 - accuracy: 0.8266 - val_loss: 0.4168 - val_accuracy: 0.8095
Epoch 10/50
5359/5359 [==============================] - 1s 141us/step - loss: 0.3938 - accuracy: 0.8330 - val_loss: 0.4122 - val_accuracy: 0.8122
Epoch 11/50
5359/5359 [==============================] - 1s 141us/step - loss: 0.3866 - accuracy: 0.8341 - val_loss: 0.4046 - val_accuracy: 0.8164
Epoch 12/50
5359/5359 [==============================] - 1s 149us/step - loss: 0.3793 - accuracy: 0.8419 - val_loss: 0.3981 - val_accuracy: 0.8228
Epoch 13/50
5359/5359 [==============================] - 1s 149us/step - loss: 0.3732 - accuracy: 0.8449 - val_loss: 0.3928 - val_accuracy: 0.8281
Epoch 14/50
5359/5359 [==============================] - 1s 142us/step - loss: 0.3675 - accuracy: 0.8503 - val_loss: 0.3883 - val_accuracy: 0.8338
Epoch 15/50
5359/5359 [==============================] - 1s 144us/step - loss: 0.3628 - accuracy: 0.8548 - val_loss: 0.3848 - val_accuracy: 0.8364
Epoch 16/50
5359/5359 [==============================] - 1s 142us/step - loss: 0.3585 - accuracy: 0.8530 - val_loss: 0.3823 - val_accuracy: 0.8387
Epoch 17/50
5359/5359 [==============================] - 1s 141us/step - loss: 0.3553 - accuracy: 0.8558 - val_loss: 0.3805 - val_accuracy: 0.8413
Epoch 18/50
5359/5359 [==============================] - 1s 143us/step - loss: 0.3522 - accuracy: 0.8593 - val_loss: 0.3790 - val_accuracy: 0.8360
Epoch 19/50
5359/5359 [==============================] - 1s 143us/step - loss: 0.3499 - accuracy: 0.8572 - val_loss: 0.3768 - val_accuracy: 0.8395
Epoch 20/50
5359/5359 [==============================] - 1s 142us/step - loss: 0.3477 - accuracy: 0.8578 - val_loss: 0.3770 - val_accuracy: 0.8383
Epoch 21/50
5359/5359 [==============================] - 1s 141us/step - loss: 0.3459 - accuracy: 0.8587 - val_loss: 0.3760 - val_accuracy: 0.8391
Epoch 22/50
5359/5359 [==============================] - 1s 141us/step - loss: 0.3443 - accuracy: 0.8587 - val_loss: 0.3744 - val_accuracy: 0.8429
Epoch 23/50
5359/5359 [==============================] - 1s 143us/step - loss: 0.3435 - accuracy: 0.8599 - val_loss: 0.3738 - val_accuracy: 0.8421
Epoch 24/50
5359/5359 [==============================] - 1s 142us/step - loss: 0.3426 - accuracy: 0.8599 - val_loss: 0.3730 - val_accuracy: 0.8444
Epoch 25/50
5359/5359 [==============================] - 1s 142us/step - loss: 0.3417 - accuracy: 0.8599 - val_loss: 0.3724 - val_accuracy: 0.8429
Epoch 26/50
5359/5359 [==============================] - 1s 143us/step - loss: 0.3409 - accuracy: 0.8600 - val_loss: 0.3718 - val_accuracy: 0.8440
Epoch 27/50
5359/5359 [==============================] - 1s 142us/step - loss: 0.3404 - accuracy: 0.8608 - val_loss: 0.3713 - val_accuracy: 0.8444
Epoch 28/50
5359/5359 [==============================] - 1s 143us/step - loss: 0.3396 - accuracy: 0.8604 - val_loss: 0.3710 - val_accuracy: 0.8436
Epoch 29/50
5359/5359 [==============================] - 1s 141us/step - loss: 0.3395 - accuracy: 0.8608 - val_loss: 0.3709 - val_accuracy: 0.8436
Epoch 30/50
5359/5359 [==============================] - 1s 143us/step - loss: 0.3389 - accuracy: 0.8593 - val_loss: 0.3702 - val_accuracy: 0.8448
Epoch 31/50
5359/5359 [==============================] - 1s 142us/step - loss: 0.3387 - accuracy: 0.8604 - val_loss: 0.3699 - val_accuracy: 0.8444
Epoch 32/50
5359/5359 [==============================] - 1s 143us/step - loss: 0.3382 - accuracy: 0.8604 - val_loss: 0.3693 - val_accuracy: 0.8451
Epoch 33/50
5359/5359 [==============================] - 1s 142us/step - loss: 0.3375 - accuracy: 0.8599 - val_loss: 0.3690 - val_accuracy: 0.8463
Epoch 34/50
5359/5359 [==============================] - 1s 148us/step - loss: 0.3374 - accuracy: 0.8612 - val_loss: 0.3684 - val_accuracy: 0.8444
Epoch 35/50
5359/5359 [==============================] - 1s 161us/step - loss: 0.3369 - accuracy: 0.8604 - val_loss: 0.3676 - val_accuracy: 0.8459
Epoch 36/50
5359/5359 [==============================] - 1s 263us/step - loss: 0.3367 - accuracy: 0.8614 - val_loss: 0.3676 - val_accuracy: 0.8455
Epoch 37/50
5359/5359 [==============================] - 2s 342us/step - loss: 0.3362 - accuracy: 0.8604 - val_loss: 0.3670 - val_accuracy: 0.8474
Epoch 38/50
5359/5359 [==============================] - 2s 334us/step - loss: 0.3359 - accuracy: 0.8608 - val_loss: 0.3675 - val_accuracy: 0.8455
Epoch 39/50
5359/5359 [==============================] - 2s 312us/step - loss: 0.3357 - accuracy: 0.8612 - val_loss: 0.3670 - val_accuracy: 0.8466
Epoch 40/50
5359/5359 [==============================] - 2s 285us/step - loss: 0.3354 - accuracy: 0.8608 - val_loss: 0.3662 - val_accuracy: 0.8512
Epoch 41/50
5359/5359 [==============================] - 2s 310us/step - loss: 0.3351 - accuracy: 0.8619 - val_loss: 0.3657 - val_accuracy: 0.8497
Epoch 42/50
5359/5359 [==============================] - 1s 270us/step - loss: 0.3349 - accuracy: 0.8606 - val_loss: 0.3662 - val_accuracy: 0.8470
Epoch 43/50
5359/5359 [==============================] - 1s 208us/step - loss: 0.3347 - accuracy: 0.8615 - val_loss: 0.3658 - val_accuracy: 0.8493
Epoch 44/50
5359/5359 [==============================] - 1s 153us/step - loss: 0.3343 - accuracy: 0.8604 - val_loss: 0.3655 - val_accuracy: 0.8519
Epoch 45/50
5359/5359 [==============================] - 1s 155us/step - loss: 0.3339 - accuracy: 0.8606 - val_loss: 0.3656 - val_accuracy: 0.8482
Epoch 46/50
5359/5359 [==============================] - 1s 166us/step - loss: 0.3338 - accuracy: 0.8614 - val_loss: 0.3653 - val_accuracy: 0.8504
Epoch 47/50
5359/5359 [==============================] - 1s 148us/step - loss: 0.3335 - accuracy: 0.8602 - val_loss: 0.3657 - val_accuracy: 0.8489
Epoch 48/50
5359/5359 [==============================] - 1s 169us/step - loss: 0.3336 - accuracy: 0.8606 - val_loss: 0.3652 - val_accuracy: 0.8474
Epoch 49/50
5359/5359 [==============================] - 1s 157us/step - loss: 0.3333 - accuracy: 0.8610 - val_loss: 0.3648 - val_accuracy: 0.8501
Epoch 50/50
5359/5359 [==============================] - 1s 158us/step - loss: 0.3331 - accuracy: 0.8614 - val_loss: 0.3650 - val_accuracy: 0.8489

In [11]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

# Calculate the Accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(y_pred,y_test)

In [12]:
score

0.8605

In [13]:
f= open("ann_acc.txt","w+")
f.write(str(round(score*100,2)))
f.close()
print("Accuracy of model is = " , round(score*100,2) ,"%")

Accuracy of model is =  86.05 %

In [14]:
classifier.save('ann_model.h5')